"""Plain-text export: a monospace report readable in any editor."""

from __future__ import annotations

from app.engines.export.base import ExportedFile, ExportPayload, exporter, fmt_num

_RULE = "=" * 72
_THIN = "-" * 72
DOC_TABLE_ROWS = 50


@exporter("txt")
def build_txt(payload: ExportPayload) -> ExportedFile:
    """Render the fit as an aligned plain-text report.

    Contains the header block, input/calculation tables (capped at
    ``DOC_TABLE_ROWS`` with a truncation note), summations, normal
    equations, numbered solution steps, equation and metrics.
    """
    fit = payload.fit
    meta = payload.meta
    lines: list[str] = [_RULE, "  CURVELAB — " + meta.title.upper(), _RULE]
    header = [
        f"  Institution : {meta.institution}" if meta.institution else None,
        f"  Course      : {meta.course}",
        f"  Author      : {meta.author}" if meta.author else None,
        f"  Student ID  : {meta.student_id}" if meta.student_id else None,
        f"  Date        : {meta.date}",
        f"  Model       : {fit.model.value} (degree {fit.degree})",
        f"  Data points : {fit.n}",
    ]
    lines += [line for line in header if line]
    lines.append(_RULE)
    lines.append("")

    lines.append("1. INPUT DATA")
    lines.append(_THIN)
    lines.append(f"{'i':>5} {'x':>14} {'y':>14}")
    for i, (xv, yv) in enumerate(zip(payload.x, payload.y), start=1):
        if i > DOC_TABLE_ROWS:
            lines.append(f"  ... first {DOC_TABLE_ROWS} of {fit.n} rows shown ...")
            break
        lines.append(f"{i:>5} {fmt_num(xv):>14} {fmt_num(yv):>14}")
    lines.append("")

    lines.append("2. SUMMATIONS")
    lines.append(_THIN)
    for s in fit.summations:
        lines.append(f"  {s.key:<12} = {fmt_num(s.value)}")
    lines.append("")

    lines.append("3. NORMAL EQUATIONS  (A · c = b)")
    lines.append(_THIN)
    for row, rhs in zip(fit.normal_equations.matrix, fit.normal_equations.vector):
        cells = "  ".join(f"{fmt_num(v):>12}" for v in row)
        lines.append(f"  [ {cells} ]  =  {fmt_num(rhs):>12}")
    lines.append("")

    lines.append("4. STEP-BY-STEP SOLUTION")
    lines.append(_THIN)
    for step in fit.steps:
        lines.append(f"  Step {step.index}: {step.title}")
        lines.append(f"    {step.description}")
    lines.append("")

    lines.append("5. RESULT")
    lines.append(_THIN)
    lines.append(f"  {fit.equation.plain}")
    for c in fit.coefficients:
        lines.append(f"  {c.name} = {fmt_num(c.value)}")
    lines.append("")

    lines.append("6. GOODNESS OF FIT")
    lines.append(_THIN)
    m = fit.metrics
    lines.append(f"  R²    = {fmt_num(m.r2)}")
    if m.adj_r2 is not None:
        lines.append(f"  adjR² = {fmt_num(m.adj_r2)}")
    lines.append(f"  RMSE  = {fmt_num(m.rmse)}")
    lines.append(f"  MAE   = {fmt_num(m.mae)}")
    lines.append(f"  MSE   = {fmt_num(m.mse)}")
    lines.append(f"  SSE   = {fmt_num(m.sse)}")
    lines.append(f"  SST   = {fmt_num(m.sst)}")
    lines.append("")
    lines.append(_RULE)
    lines.append("  Generated by CurveLab — Least Squares Curve Fitting")
    lines.append(_RULE)

    return ExportedFile("\n".join(lines).encode("utf-8"), "text/plain", "txt")
